version: '3.8'

services:
  app:
    build: .
    container_name: nestjs-app
    restart: always
    ports:
      - "8080:8888"
    environment:
      - DB_HOST=116.205.136.171
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD='@schuck_d_998'
      - DB_NAME=blog
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '@schuck_d_998'
      MYSQL_DATABASE: blog
    volumes:
      - mysql_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "8081:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

volumes:
  mysql_data: